---
apiVersion: extensions/v1beta1
kind: Service
apiVersion: v1
metadata:
  labels:
    service: memcached
  name: memcached
  namespace: FQ_NAMESPACE
spec:
  type: ClusterIP
  selector:
    app: memcached
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
      name: memcached 